# Generated by Django 5.1.7 on 2025-03-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, help_text='Optional external link (e.g., SumUp, Eventbrite, or Google Form)'),
        ),
    ]
