# Generated by Django 5.1.7 on 2025-03-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_label',
            field=models.CharField(blank=True, choices=[('book', 'Book Now'), ('signup', 'Sign Up'), ('learn', 'Learn More')], help_text='Button label for the link', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, help_text='External link (e.g., SumUp, Eventbrite, Google Form)'),
        ),
    ]
