# Generated by Django 5.1.7 on 2025-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_link_label_alter_post_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='funders/')),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField()),
                ('contact_description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('opening_hours', models.TextField(help_text='Use line breaks to separate days.')),
            ],
        ),
    ]
