# Generated by Django 5.1.7 on 2025-03-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_funder_infopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='color',
            field=models.CharField(default='#000000', help_text='Hex color code for this category, e.g. #FF5733', max_length=7),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='signup_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='video_embed_code',
            field=models.TextField(blank=True),
        ),
    ]
