# Generated by Django 5.1.7 on 2025-03-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_funder_website_funder_project_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funder',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='funders/'),
        ),
        migrations.AlterField(
            model_name='funder',
            name='project_categories',
            field=models.ManyToManyField(blank=True, to='main.projectcategory'),
        ),
    ]
