# Generated by Django 5.1.7 on 2025-03-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_funder_logo_alter_funder_project_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funder',
            name='project_categories',
            field=models.ManyToManyField(blank=True, related_name='funders', to='main.projectcategory'),
        ),
    ]
