# Generated by Django 5.1.7 on 2025-03-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_funder_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='mission_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='support_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='team',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
