# Generated by Django 5.1.7 on 2025-03-26 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_infopage_mission_text_infopage_support_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopage',
            name='team',
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('description', models.TextField()),
                ('info_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='main.infopage')),
            ],
        ),
    ]
