# Generated by Django 5.1.7 on 2025-03-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_infopage_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
