# Generated by Django 5.1.7 on 2025-03-26 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teammember_job_title_alter_teammember_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='info_page',
        ),
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='main.projectcategory'),
            preserve_default=False,
        ),
    ]
