# Generated by Django 5.1.7 on 2025-03-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_teammember_info_page_teammember_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='category',
        ),
        migrations.AddField(
            model_name='teammember',
            name='info_page',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this team member is for a specific category only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='main.infopage'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='project_category',
            field=models.ForeignKey(blank=True, help_text='Assign this team member to a specific category (e.g. Radio Dyfi). Leave blank if general staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='main.projectcategory'),
        ),
    ]
