# Generated by Django 5.1.5 on 2025-09-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_teammember_category_teammember_info_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, help_text="Vertical poster used on the What's On page.", null=True, upload_to='projects/posters/')),
                ('horizontal_image', models.ImageField(blank=True, help_text='Horizontal image or banner used in the modal.', null=True, upload_to='projects/horizontal/')),
                ('video_embed_code', models.TextField(blank=True, help_text='Embed code for a video/trailer.')),
                ('link', models.URLField(blank=True, help_text='External link for booking, signup, etc.')),
                ('link_label', models.CharField(blank=True, choices=[('book', 'Book Now'), ('signup', 'Sign Up'), ('learn', 'Learn More')], max_length=20)),
                ('color', models.CharField(default='#000000', help_text='Hex color for modal accents.', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='info_page',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='project_category',
        ),
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_sections', to='main.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Funder',
        ),
        migrations.DeleteModel(
            name='InfoPage',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
