# Generated by Django 5.1.5 on 2025-09-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_project_remove_teammember_info_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_label',
            field=models.CharField(blank=True, choices=[('book', 'Book Now'), ('signup', 'Sign Up'), ('learn', 'Learn More')], default='learn', max_length=20),
        ),
    ]
