# Generated by Django 5.1.5 on 2025-09-07 10:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_project_link_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosection',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this section (e.g., header photo)', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='is_links_section',
            field=models.BooleanField(default=False, help_text='Check if this section should display as a list of links'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_1_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_1_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_2_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_2_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_3_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_3_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_4_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_4_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='horizontal_image',
            field=models.ImageField(blank=True, help_text='Horizontal image or banner used in the modal.', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/horizontal/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ImageField(blank=True, help_text="Vertical poster used on the What's On page.", null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/posters/'),
        ),
    ]
