# Generated by Django 5.1.5 on 2025-09-07 10:24

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_infosection_image_infosection_is_links_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunderLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a funder/supporter logo.', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/funders/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder_logos', to='main.infosection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
