# Generated by Django 5.1.5 on 2025-09-07 10:27

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_funderlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosection',
            name='funder_logo_1',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/funders/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='funder_logo_2',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/funders/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='funder_logo_3',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/funders/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='funder_logo_4',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/funders/'),
        ),
        migrations.DeleteModel(
            name='FunderLogo',
        ),
    ]
