# Generated by Django 5.1.5 on 2025-09-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_infosection_funder_logo_1_infosection_funder_logo_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='volunteer_label',
            field=models.CharField(blank=True, default='Sign Up', help_text="Label for the volunteer button (default: 'Sign Up')", max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='volunteer_link',
            field=models.URLField(blank=True, help_text='Link to volunteer sign-up form (Google Form or internal page)'),
        ),
    ]
