# Generated by Django 5.1.5 on 2025-09-07 13:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_project_volunteer_label_project_volunteer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_1',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_10',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_11',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_12',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_13',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_14',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_15',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_16',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_17',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_18',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_19',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_2',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_20',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_3',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_4',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_5',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_6',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_7',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_8',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AddField(
            model_name='infosection',
            name='carousel_image_9',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
        migrations.AlterField(
            model_name='infosection',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional main image for this section', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='info/sections/'),
        ),
    ]
