# Generated by Django 5.1.5 on 2025-09-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_infosection_carousel_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosection',
            name='link_10_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_10_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_5_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_5_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_6_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_6_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_7_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_7_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_8_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_8_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_9_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='infosection',
            name='link_9_url',
            field=models.URLField(blank=True),
        ),
    ]
